services:
  db:
    image: postgres:16
    container_name: emlak_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emlak
    ports:
      - "5432:5432"
